# Path, directories
path_movie: data/current_observation.mp4 # [str] path of the input movie (must be a mp4 file)
dir_tmp: scratch # [str] temporary directory to save temporary files
dir_out: output # [str] output directory
file_out: currents.nc # [str] output netcdf filename 

# Preprocessing
resolution_movie: 0.0342 # [float] movie pixel size (in meter)
fps: 10 # [int] number of frame per seconds to extract
band: 0 # [int] RGB band to select (1, 2 or 3)
flag_downscale_movie: True # [bool] downscale the movie to increase computation time
downscaling: 3 # [int] dowscaling factor

# Current estimation
num_pixels: 128 # [int] number of pixels to consider for one current estimation
accuracy: 0.01  # [float] accuracy of the estimated current velocities (in m/s)
ulim: [-1,1] # [list] Range of u-component in which the optimization is performed (in m/s)
vlim: [-1,1] # [list] Range of v-component in which the optimization is performed (in m/s)
du: .1 # [float] initial step to optimize a first estimate of the u-component (in m/s)
dv: .1 # [float] initial step to optimize a first estimate of the u-component (in m/s)
norm: False # [bool] normalize the spectra
w0: .6 # [float] lower bound of the time frequency (in Hz)
w1: .9 # [float] upper bound of the time frequency (in Hz)
ub: 0. # [float] u-component first guess (in m/s)
vb: 0. # [float] v-component first guess (in m/s)

# Parallelization
num_threads: 16 # [int] number of threads to run in parallel (set the maximum, the computations are quiet long!)
